
version: '3.7'

services:
  
  db: # 1st service
    image: mysql:5.7

    container_name: mysql_db
    volumes:
      - db_data:/var/lib/mysql # we are mounting a collecting the data of the mysql db in a local folder db_data
    ports:
     - "3305:3306"   
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root@wordpress
        MYSQL_DATABASE: mywordpr
        MYSQL_USER: wp_user  # This user should be the same as the one given to wordpress_DB_ environment
        MYSQL_PASSWORD: abc@123 # here also same / equals to WORDPRESS_DB_PASSWORD (password Wordpress will use to connect to the Db)

  wordpress: # 2nd service our Frontend 

      depends_on: # create a relation with the db service 
        - db
      image: wordpress:latest
      container_name: wd_frontend
      volumes:
        - wordpress_files:/var/www/html 
      ports:
        - "9000:80"
      restart: always
      environment:
        WORDPRESS_DB_HOST: db
        WORDPRESS_DB_USER: wp_user
        WORDPRESS_DB_PASSWORD: abc@123
        WORDPRESS_DB_NAME: mywordpr
volumes:
    wordpress_files:
    db_data:
 

# Checking all configuration use The in current folder:
##--->  docker-compose config   

# Running it in the current folder with: 
##--->   " docker-compose up -d ."

# To get logs of The running containers:
##-->    " docker-compose logs -f  ""